In [1]:
import numpy as np

In [2]:
a = np.array([20, 40, 60])
b = np.array([10, 20, 30])
c = np.array([5, 10, 15, 20])

In [3]:
# Vector addition
a + b

array([30, 60, 90])

In [4]:
# Vector subtraction
a - b

array([10, 20, 30])

In [5]:
# Vector multiplication
a * b

array([ 200,  800, 1800])

In [6]:
# Vector divison
a - b

array([10, 20, 30])

In [8]:
# Scalar x Vector
scalar = 2
a_list_vector = [10, 20, 30]
# Scalar x list vector repeats the list
scalar * a_list_vector

[10, 20, 30, 10, 20, 30]

In [10]:
# Scalar x Vector
scalar = 2
a_numpy_array_vector = np.array([10, 20, 30])
# Scalar x numpy array vector gives the required result
scalar * a_numpy_array_vector

array([20, 40, 60])