### 1. Basics

In [1]:
import numpy as np
from numpy import linalg

In [2]:
a = np.array([20, 40, 60])
b = np.array([10, 20, 30])
c = np.array([5, 10, 15, 20])

In [3]:
# Vector addition
a + b

array([30, 60, 90])

In [4]:
# Vector subtraction
a - b

array([10, 20, 30])

In [5]:
# Vector multiplication
a * b

array([ 200,  800, 1800])

In [6]:
# Vector divison
a - b

array([10, 20, 30])

In [7]:
# Scalar x Vector
scalar = 2
a_list_vector = [10, 20, 30]
# Scalar x list vector repeats the list
scalar * a_list_vector

[10, 20, 30, 10, 20, 30]

In [8]:
# Scalar x Vector
scalar = 2
a_numpy_array_vector = np.array([10, 20, 30])
# Scalar x numpy array vector gives the required result
scalar * a_numpy_array_vector

array([20, 40, 60])

### Dot Product of Vectors

In [9]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = np.array([11, 12, 13, 14, 15])

In [10]:
# Dot product
np.dot(x, y)

130

In [11]:
# Dot product commutative
np.dot(y, x)

130

In [12]:
# Dot product distributive
print(np.dot(x, y + z))
print(np.dot(x, y) + np.dot(x, z))

335
335


### Scalar and Vector Projection

In [13]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([60, 70, 80, 90, 100])

In [14]:
# Norm
linalg.norm(a)

74.16198487095663

In [15]:
# Vector project of a onto b
scalar_projection = (np.dot(a, b) / np.dot(b, b))
# In order to get vector project we multiply the scalar projection with unit vector of b
vector_projection = scalar_projection * b
# (np.dot(a, b) / np.dot(b, b)) * b -> In one step
print('Scalar projection:', scalar_projection)
print('Vector projection:', vector_projection)

Scalar projection: 0.3939393939393939
Vector projection: [23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]
