### Gaussian Elimination and Finding the Inverse Matrix

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
print('Matrix A:', A)
print('Vector b:', b)

Matrix A: [[1 2]
 [3 4]]
Vector b: [ 5 11]


In [3]:
# Solving by A * x = b

# Find A_inv -> A * A_inv * x = A_inv * b -> x = A_inv * b
# 1. Find A_inv
A_inv = np.linalg.inv(A)
# 2. Find x
x = np.dot(A_inv, b)
x

array([1., 2.])

In [4]:
# Verify the solution with A * x = b
np.dot(A, x) # should be equal to vector b

array([ 5., 11.])

### Inverse and Determinant

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 2], [3, 2]])

In [6]:
# Non singular matrix - Determinant non zero -> A_inv cannot be computed
np.linalg.det(A)

-2.0000000000000004

In [7]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
# Singular matrix - Determinant zero -> A_inv cannot be computed
np.linalg.det(B)

0.0